[B2BP-316] Avoid html suffix to be added to .woff2
pagopa/b2b-portals pull request #128
Opened 2024-01-15 10:37 UTC by Meolocious

#### List of Changes
- Fixed the `file viewer-request-handler.ts` to handle requests, preventing the addition of ".html" to ".woff2" files.
- Updated the `viewer-request-handler.test.ts` test file to align with the recent changes.

#### Motivation and Context
This change is necessary to address a specific issue where the `file viewer-request-handler.ts` was incorrectly handling requests, leading to the unintended addition of ".html" to ".woff2" files. The fix ensures that this behavior is corrected, providing a more reliable file handling mechanism.

#### How Has This Been Tested?
I have thoroughly tested these changes in a controlled environment. The testing involved checking the behavior of the `viewer-request-handler.ts` when handling requests related to ".woff2" files. Additionally, the `viewer-request-handler.test.ts` file was updated to reflect the recent changes and to ensure the accuracy of the tests.

Testing Environment:
- Operating System: Windows 10
- Node.js version: 20.10.0

#### Types of changes
- [ ] Chore (nothing changes from a user perspective)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Doesn't need any documentataion changes.

2024-01-15 10:50 UTC, kin0992 commented on apps/cloudfront-functions/src/viewer-request-handler.ts
> +export const handler = (
You cannot use the `export` keyword here. Doing this, you are kind of reverting [this PR that fixed the issue](https://github.com/pagopa/b2b-portals/pull/125).

If you use the `export` there, you will get a runtime error on the function

2024-01-15 14:36 UTC, kin0992 requested changes

2024-01-15 14:36 UTC, kin0992 commented on apps/cloudfront-functions/package.json
> +    "test": "npm run compile && vitest"
This is not necessary: there is the `pretest` script that does what you want.

Reference: https://docs.npmjs.com/cli/v9/using-npm/scripts#pre--post-scripts

2024-01-15 14:54 UTC, simosalsi requested changes

2024-01-15 14:54 UTC, simosalsi commented on apps/cloudfront-functions/src/viewer-request-handler.ts
> +      !/\.[a-zA-Z]+$/.test(uri)
```suggestion
      !/\.[0-9a-zA-Z]+$/.test(uri)
```

I would just make this more generic and prevent the program from adding '.html' to any url ending in any extension which contains letters or numbers (hence including .woff2)

2024-01-15 15:24 UTC, simosalsi commented on apps/cloudfront-functions/src/__tests__/viewer-request-handler.test.ts
> +    expect(handler(makeEvent(example1)).uri).toBe(example1);
Is this the desired behaviour?

I think it's fine, but I just wanted to gather consensus.

2024-01-15 15:26 UTC, simosalsi requested changes

2024-01-15 15:26 UTC, simosalsi commented on apps/cloudfront-functions/src/viewer-request-handler.ts
> +      !uri.endsWith('.woff2') &&
```suggestion
```
Redundant

2024-01-15 16:09 UTC, simosalsi commented on apps/cloudfront-functions/src/viewer-request-handler.ts
> +    // Add the .html extension if missing and the uri does not end with .woff2
```suggestion
    // Add the .html extension if missing
```
I don't think there's a need to specify .woff2. It shows from tests.

2024-01-15 16:09 UTC, simosalsi approved these changes

2024-01-22 12:09 UTC, simosalsi commented on .changeset/perfect-cycles-care.md
> +manage the ".html" extension to not be added improperly
```suggestion
prevent the ".html" extension being added to any url ending in an extension (.jpg, .html, .woff2, etc...)
```
I would go for something a little more specific as per suggestion.

2024-01-22 16:21 UTC, datalek approved these changes

2024-01-22 17:00 UTC, merged