commit bannerlink component
pagopa/b2b-portals pull request #130
Opened 2024-01-16 09:50 UTC by Meolocious

#### List of Changes
- Added a new component called `BannerLink` in `components\Bannerlink.tsx`.
- Managed the usage of `BannerLink` in `components\PageSection\PageSection.tsx`.
- Added the `BannerLink` codec in `lib\fetch\types\PageSection.ts`.

#### Motivation and Context
This PR introduces a new component, `BannerLink`, aimed at enhancing the structure and functionality of our Next.js website. The addition of this component is necessary to build the "enti" page on our website.

#### How Has This Been Tested?
I have thoroughly tested these changes in my development environment. The testing involved:
- Confirming the proper functionality of the newly added `BannerLink` component.
- Verifying that the integration of the `BannerLink` component in `PageSection.tsx` works seamlessly.
- Ensuring that the `BannerLink` code in `sectionDataToProps.tsx` correctly handles data from API calls.

#### Types of changes
- [ ] Chore (nothing changes from a user perspective)
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Doesn't need any documentation updates

2024-01-17 13:34 UTC, simosalsi commented on apps/nextjs-website/src/components/Bannerlink.tsx
> +import React from 'react';
```suggestion
```
This import isn't needed

2024-01-17 13:36 UTC, simosalsi approved these changes

2024-01-18 14:12 UTC, kin0992 commented
@simosalsi @Meolocious please add the changeset following [what the Bot is suggesting](https://github.com/pagopa/b2b-portals/pull/130#issuecomment-1893402177) or [following the instructions available in the README](https://github.com/pagopa/b2b-portals/?tab=readme-ov-file#changelog) 🙏

2024-01-24 11:22 UTC, kin0992 commented on .changeset/old-planes-hang.md
> +Implementing BannerLink component from Editorial-Components repository
```suggestion
Implement BannerLink component from Editorial-Components library
```
Start the sentence in the imperative way

2024-01-24 11:22 UTC, kin0992 commented on apps/nextjs-website/src/lib/fetch/types/PageSection.ts
> +  ),
```suggestion
  ctaButtons: t.array(CTAButtonSchema),
```
is it possible to use the `CTAButtonSchema` instead?

2024-01-25 09:29 UTC, datalek requested changes

2024-01-25 10:15 UTC, simosalsi commented on apps/nextjs-website/src/lib/fetch/types/PageSection.ts
> +  decoration: t.union([ImageDataCodec, t.null]),
Implementation here is correct.

decoration is always undefined due to missing parameter in fetching query.

Fixing ASAP

2024-01-25 10:40 UTC, simosalsi commented on apps/nextjs-website/src/components/Bannerlink.tsx
> +  body: MarkdownRenderer({ markdown: body, variant: 'body2' }),
Adding any tag that's not a text-altering tag such `em` inside a `p` tag gives this error.

Unfortunately BannerLink puts the `body` parameter's contents inside a `p` tag (this does not happen for other components btw).

Only solution possible atm is just not rendering the `body` parameter's contents.

Fix is already pushed.

2024-01-25 14:36 UTC, datalek commented on apps/nextjs-website/src/components/Bannerlink.tsx
> +  body: MarkdownRenderer({ markdown: body, variant: 'body2' }),
Absolutely clear. How about opening a bug under the epic [B2BP-344](https://pagopa.atlassian.net/browse/B2BP-344) and referencing the ticket on the line in this PR that we'll change once the issue is fixed to add the markdown?

2024-01-25 14:44 UTC, datalek commented on apps/strapi-cms/src/components/sections/banner-link.json
I would add the changelog for `strapi-cms` as well since it's being modified.

2024-01-25 14:44 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/navigation.ts
> +      `${config.STRAPI_API_BASE_URL}/api/navigation/render/${menuName}?type=FLAT&populate[sections][populate][0]=ctaButtons&populate[sections][populate][1]=image&populate[sections][populate][2]=backg
Since it might be unclear why we need to add these query parameters, I would add a comment explaining the reason.

2024-01-25 14:46 UTC, simosalsi commented on apps/nextjs-website/src/components/BannerLink.tsx
> +});
Due to a bug in the BannerLink component we are not currently rendering the `body` parameter as HTML as we would like.

[A task](https://pagopa.atlassian.net/browse/B2BP-354) has been created to address the issue.

Once the issue has been resolved, we'll render `body` as we should.

2024-01-26 08:30 UTC, kin0992 approved these changes

2024-01-26 13:17 UTC, datalek approved these changes
LGTM

2024-01-26 14:28 UTC, datalek approved these changes

2024-01-26 14:38 UTC, merged