[B2BP-337] Added Update Static Content plugin for static site deployment
pagopa/b2b-portals pull request #140
Opened 2024-01-23 15:24 UTC by simosalsi

Added Update Static Content plugin for static site deployment.

[RFC](https://pagopa.atlassian.net/wiki/spaces/SV/pages/903151626/SV-014+Avviare+il+re+deploy+del+sito+statico+da+Strapi) for reference.

#### List of Changes

- Installed plugin
- Configured plugin
- Updated .env.example

#### Motivation and Context

Needed to give CMS users the chance to trigger redeployment.

#### How Has This Been Tested?

Inside a production-equivalent AWS environment.

#### Screenshots (if appropriate):
![Screenshot (19)](https://github.com/pagopa/b2b-portals/assets/59611877/3819693e-5d7b-4871-a3e8-5ff3cea7c27f)

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-23 15:27 UTC, simosalsi commented
@maurodandrea 

We may need a new PR to add the environment variables needed for this to work.

Namely the following:
GITHUB_PAT
REPO_OWNER
REPO_NAME
WORKFLOW_ID
TARGET_BRANCH

All except for GITHUB_PAT are currently optional, as they have a default value.

However we may not need some of these at all: If the above mentioned "default values" are sure to be the only possible values we may as well hard-code them in.

2024-01-24 10:29 UTC, maurodandrea commented
Depends on https://github.com/pagopa/b2b-portals/pull/142

2024-01-24 10:43 UTC, datalek requested changes

2024-01-24 10:43 UTC, datalek commented on .changeset/spicy-bats-wash.md
> +Added Update Static Content plugin for static site deployment
```suggestion
"strapi-cms": minor
---

Add Update Static Content plugin for static site deployment
```

2024-01-24 11:16 UTC, kin0992 approved these changes
👍

2024-01-24 11:17 UTC, kin0992 approved these changes
👍

2024-01-24 11:23 UTC, maurodandrea approved these changes

2024-01-24 15:43 UTC, datalek approved these changes

2024-01-24 15:46 UTC, datalek approved these changes

2024-01-24 15:46 UTC, merged