Pr IFrame Component
pagopa/b2b-portals pull request #270
Opened 2024-05-10 14:00 UTC by salvatorediocaro

#### List of Changes

Created the IFrame.tsx and IFrame.types.ts files

#### Motivation and Context

Import the content of an external page via IFrame

#### How Has This Been Tested?

Execute on locally B2B-Portals

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-23 12:17 UTC, simosalsi requested changes

2024-05-23 12:17 UTC, simosalsi commented on apps/nextjs-website/src/components/IFrame.tsx
> +const IFrame = (props: IFrameSectionProps) => (
```suggestion
const IFrameSection = (props: IFrameSectionProps) => (
```
For consistency

2024-05-23 12:17 UTC, simosalsi commented on apps/nextjs-website/src/components/IFrame.tsx
> +export default IFrame;
```suggestion
export default IFrameSection;
```
For consistency

2024-05-23 12:17 UTC, simosalsi commented on apps/nextjs-website/react-components/components/IFrame/iframe-resizer.d.ts
Why is this needed?

2024-05-23 15:10 UTC, simosalsi submitted a review, later dismissed

2024-05-23 15:33 UTC, maurodandrea submitted a review, later dismissed

2024-06-04 13:54 UTC, simosalsi approved these changes
Approving to demo the iFrame

Commented code inside iFrame will be reinstated when client side issues are resolved.

2024-06-04 16:11 UTC, simosalsi approved these changes
Approving to demo the iFrame

Commented code inside iFrame will be reinstated when client side issues are resolved.

2024-06-04 16:12 UTC, merged