[B2BP-602] - Storybook
pagopa/b2b-portals pull request #274
Opened 2024-05-13 09:35 UTC by Meolocious

#### List of Changes
- Created a the storybook structure
- Implemented Colours
- Implemented Typography
- Implemented Hero component from RC

#### Motivation and Context
This PR is made to use the Storybook for visualizing components

#### How Has This Been Tested?
Tested locally

#### Types of changes
- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] Doesn't need any documentation update.

2024-05-21 09:50 UTC, simosalsi requested changes

2024-05-21 09:50 UTC, simosalsi commented on .changeset/shiny-months-reply.md
> +Creating Storybook for B2BP RC components
```suggestion
Create Storybook for B2BP RC components
```

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/.storybook/main.ts
> +import { join, dirname } from "path";
```suggestion
import { join, dirname } from "path";
```

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/.storybook/main.ts
> +  ],
Are these all necessary or just from a standard configuration?

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/.storybook/main.ts
> +  staticDirs: ["../public"],
Are we using any static assets currently?

If we aren't, can we remove this?

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/.storybook/preview.tsx
> +    },
Are these necessary?

I don't think we have any colors or dates to be inserted and the matchers appear to be [the default ones](https://storybook.js.org/docs/essentials/controls#custom-control-type-matchers) anyway.

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/stories/Buttons/dark.stories.ts
> +}
Probably move this to a `buttonsCommons.tsx` file similar to `heroCommons.tsx`

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/stories/Buttons/dark.stories.ts
> +  },
Since this is all the same for light and dark I would move this to `buttonsCommons.tsx` as well

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/stories/Hero/dark.stories.tsx
> +];
This should be fine in `heroCommons.tsx`

2024-05-21 09:50 UTC, simosalsi commented on apps/nextjs-website/stories/Hero/dark.stories.tsx
> +  background: 'https://notifichedigitali.pagopa.it/static/images/hero-enti-background.png',
The value for these can go into `heroCommons.tsx` as well

2024-05-21 14:00 UTC, simosalsi requested changes

2024-05-21 14:00 UTC, simosalsi commented on apps/nextjs-website/package.json
> +    "@storybook/test": "^8.1.0",
```suggestion
    "@storybook/nextjs": "^8.1.0",
    "@storybook/react": "^8.1.0",
```
I don't see the two removed used anywhere

2024-05-22 07:09 UTC, simosalsi approved these changes

2024-05-22 07:13 UTC, maurodandrea approved these changes

2024-05-22 07:28 UTC, christian-calabrese approved these changes
LGTM

2024-05-22 07:29 UTC, merged