[B2BP-115] Removed extends inside Strapi's tsconfig files
pagopa/b2b-portals pull request #77
Opened 2023-11-20 13:24 UTC by simosalsi

Removed extends inside Strapi's tsconfig files and manually copied extended configurations.

#### List of Changes

#### Motivation and Context

Could not deploy folder /apps/strapi-cms/ on its own otherwise.

#### How Has This Been Tested?

On a private ECS instance.

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-11-20 14:49 UTC, kin0992 requested changes

2023-11-20 14:49 UTC, kin0992 commented on apps/strapi-cms/tsconfig.json
> +
```suggestion
```

2023-11-20 14:49 UTC, kin0992 commented on apps/strapi-cms/src/admin/tsconfig.json
```suggestion
```

2023-11-22 09:36 UTC, datalek approved these changes

2023-11-23 07:52 UTC, kin0992 approved these changes

2023-11-23 07:52 UTC, merged