[B2BP-179] - Implementing Header as generic component
pagopa/b2b-portals pull request #78
Opened 2023-11-20 14:54 UTC by Meolocious

#### List of Changes
- Created `Header.tsx` component inside the `components` folder to isolate the 'use client' side only for the component itself.
- Added `Header.ts` file for fetching data from the CMS API call, utilizing io-ts for validation.
- Introduced `Menu.ts` file to populate the menu part of the header with routes obtained from `navigation.ts`.
- Included `Header.test.ts` file for testing the API call using `vitest`.

#### Motivation and Context
The motivation behind these changes is to enhance the structure and maintainability of our codebase. By creating the `Header.tsx` component, we isolate client-side logic for better organization and modularity. The addition of `Header.ts` ensures a reliable and validated approach to fetching data from the CMS API, employing io-ts for robust data validation. The `menu.ts` file contributes to filling the header menu with routes obtained from `navigation.ts`, providing a seamless and dynamic user experience. The testing file, `Header.test.ts`, validates the API call using `vitest`, ensuring the functionality is robust and dependable.

#### How Has This Been Tested?
Comprehensive testing has been conducted to validate the effectiveness and reliability of these changes. The `Header.test.ts` file includes a suite of tests for the API call, covering various scenarios and edge cases. Additionally, the testing environment has been carefully configured to assess how these changes impact other areas of the code. This includes integration tests to ensure the seamless interaction between components, API calls, and data validation.

#### Types of changes
- [ ] Chore (nothing changes from a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Doesn't need any documentation updates.

2023-11-22 08:13 UTC, datalek requested changes

2023-11-22 08:13 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/types/ctaButtons.ts
Rename the file to `CtaButton.ts`

2023-11-22 08:13 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/types/ctaButtons.ts
> +export const CtaGroupCodec = t.intersection([
Move CtaGroupCodec to `src/lib/fetch/types/CtaGroup.ts`

2023-11-22 08:13 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/menu.ts
Move this function to `src/lib/menu.ts` because it does not use `fetch`

2023-11-22 08:13 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/menu.ts
Add some test to `makeMenuFromNavigation`

2023-11-22 16:22 UTC, datalek requested changes

2023-11-22 16:22 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/__tests__/header.test.ts
> +};
```suggestion
const headerResponse = {
  data: {
    attributes: {
      productName: 'Test',
      beta: false,
      reverse: false,
      theme: 'light',
      avatar: {
        data: {
          attributes: {
            url: '/uploads/file_e4c03befba.png',
            alternativeText: null,
          },
        },
      },
      ctaButtons: [
        {
          text: 'test',
          href: '/',
          variant: 'text',
          color: 'inherit',
          icon: null,
          size: 'medium',
        },
      ],
    },
  },
};
```

2023-11-22 16:22 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/types/StrapiImage.ts
> +});
Use strict to have the output that contains only the defined attributes

```suggestion
export const StrapiImageSchema = t.strict({
  data: t.union([
    t.strict({
      attributes: t.strict({
        alternativeText: t.union([t.string, t.null]),
        url: t.string,
      }),
    }),
    t.null,
  ]),
});
```

2023-11-22 16:22 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/types/CtaButton.ts
> +export type ctaButtons = t.TypeOf<typeof CTAButtonSchema>;
Never used

```suggestion
```

2023-11-22 16:22 UTC, datalek commented on apps/nextjs-website/src/lib/fetch/types/CtaButton.ts
Keep the same naming convention (rename the file from `CtaButton` to `CTAButton`)

2023-11-23 13:54 UTC, kin0992 requested changes

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/__tests__/header.test.ts
> +import { makeHeaderProps } from '../header'; // Adjust the import path based on your file structure
🤔

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/header.ts
> +      href: '/' + item.path + '/' + child.path,
```suggestion
      href: `/${item.path}/${child.path}`,
```

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/header.ts
> +    href: '/' + path,
```suggestion
    href: `/${path}`,
```

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/__tests__/header.test.ts
> +            alternativeText: 'Alt text', // Add this line if alternativeText is part of your data structure
```suggestion
            alternativeText: 'Alt text',
```
is it a part of the structure or not? 🤔
do we want it to be tested or not?

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/__tests__/header.test.ts
> +};
move these common structures in a file called `data.ts` under the `__tests__` folder. These structures are used also in other tests

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/__tests__/header.test.ts
> +      ], // You may need to adjust this based on your specific implementation
```suggestion
      ],
```

2023-11-23 13:54 UTC, kin0992 commented on apps/nextjs-website/src/lib/__tests__/header.test.ts
> +      ], // You may need to adjust this based on your specific implementation
```suggestion
      ],
```

2023-11-27 11:38 UTC, kin0992 approved these changes

2023-11-27 11:39 UTC, datalek approved these changes

2023-11-27 11:39 UTC, merged