[B2BP-181] - Implementing Editorial as home component
pagopa/b2b-portals pull request #84
Opened 2023-11-27 16:28 UTC by Meolocious

#### List of Changes
1. Created `Editorial.tsx` file for the component to avoid 'use case' spread everywhere in Next.js.
2. Created the file `rendering.tsx` to manage the switch case. Currently, only the editorial component is available.
3. Created `sectionDataToProps.tsx` to convert data from the API call to the component itself.

#### Motivation and Context
This PR introduces three new files to enhance the structure and maintainability of our codebase. The `Editorial.tsx` file addresses the issue of 'use case' being scattered throughout the code in Next.js. Additionally, the `rendering.tsx` file provides a structured approach to handle different cases, starting with the editorial component. Finally, `sectionDataToProps.tsx` is introduced to facilitate the conversion of data from API calls to the respective component.

#### How Has This Been Tested?
I have tested these changes thoroughly in my development environment. The testing involved:
- Verifying the proper functionality of the `Editorial.tsx` component.
- Ensuring the switch case in `rendering.tsx` works correctly for the existing editorial component.
- Validating that `sectionDataToProps.tsx` successfully converts data from API calls to the component.

#### Types of changes
- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Doesn't need any documentation updates.

2023-12-05 14:44 UTC, simosalsi submitted a review, later dismissed

2024-01-04 11:57 UTC, Meolocious commented
"rendering" folder is the old one. After shifting elements from the sectionDataToProps.tsx to the main component, the folder could be deleted

2024-01-04 16:37 UTC, datalek requested changes
To be adapted according to what has been done for https://github.com/pagopa/b2b-portals/pull/83.

2024-01-08 16:33 UTC, datalek approved these changes
LGTM

2024-01-08 16:34 UTC, merged