[B2BP-249] Added styling for Hero
pagopa/b2b-portals pull request #96
Opened 2023-12-21 09:46 UTC by Meolocious

#### List of Changes
- Updated Hero.tsx to address style issues.
- Modified layout.tsx to fix font styles.

#### Motivation and Context
This change is necessary to address style-related issues in the Hero and layout components. The Hero.tsx file was modified to fix the styling problem, and adjustments were made in the layout.tsx file to ensure consistent font styles throughout the application.

#### How Has This Been Tested?
The changes have been tested thoroughly to ensure that the style issues are resolved and that there are no unintended consequences. Testing included verification of the appearance and behavior of affected components in various scenarios. Specific test cases included [describe any specific test scenarios or steps performed].

#### Types of changes
- [ ] Chore (nothing changes from a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Doesn't need any documentation changes.

2024-01-04 16:39 UTC, datalek requested changes
To be adapted according to what has been done for https://github.com/pagopa/b2b-portals/pull/83.

2024-01-08 16:48 UTC, datalek requested changes

2024-01-09 09:59 UTC, simosalsi commented on apps/nextjs-website/src/utils.ts
> +};
This is used as of the latest commit

2024-01-09 15:34 UTC, datalek approved these changes

2024-01-09 15:34 UTC, datalek commented on apps/nextjs-website/src/utils.ts
File named `util`, `common`, or `misc` provide no sense of what the file contains. This makes it harder for devs to use the file and makes it harder for maintainers to keep the file focused. 
I would rename it to `icons.ts`, or place it inside the `components` folder, within an `Icons` subfolder, in an index.ts file (`components/Icons/index.ts`).

2024-01-09 16:24 UTC, datalek approved these changes
LGTM

2024-01-09 16:24 UTC, merged